import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-red-400 backdrop-blur min-h-screen`} style={{
        background: 'var(--background-gradient, linear-gradient(180deg, rgba(248, 113, 113, 1) 0%, rgba(255, 207, 36, 1) 100%))',
        backdropFilter: 'blur(2px)'
      }}>
        <Navbar />
        <div >{children}</div>
       
      </body>
    </html >
  );
}
